# Generated by Django 3.2.8 on 2021-12-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seeker_reg',
        ),
    ]
