# Generated by Django 3.2.8 on 2021-12-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0010_alter_emplor_postjob_experiance'),
        ('usermodule', '0003_seeker_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyjob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employermodule.emplor_reg')),
                ('jobid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employermodule.emplor_postjob')),
                ('seeker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermodule.seeker_reg')),
            ],
        ),
    ]
