# Generated by Django 3.2.8 on 2021-12-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0004_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='employer',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
