# Generated by Django 3.2.8 on 2021-12-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0005_alter_applyjob_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='jobid',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='seeker',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
