# Generated by Django 3.2.8 on 2022-01-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0007_blog_se'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_se',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
