# Generated by Django 3.2.8 on 2022-01-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0008_blog_se_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=200, null=True)),
                ('cemail', models.CharField(max_length=1500, null=True)),
                ('cphone', models.CharField(max_length=150, null=True)),
                ('cmessage', models.CharField(max_length=150, null=True)),
                ('seeker', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
