# Generated by Django 3.2.8 on 2021-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emplor_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=50)),
                ('epassword', models.CharField(max_length=50)),
                ('emobilenumber', models.CharField(max_length=100)),
            ],
        ),
    ]
