# Generated by Django 3.2.8 on 2021-12-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='em_img',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('simg', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='emplor_cmre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ecname', models.CharField(max_length=100)),
                ('ecemail', models.CharField(max_length=50)),
                ('ecmobilenumber', models.CharField(max_length=50)),
                ('ecaddress', models.CharField(max_length=50)),
                ('ecwebsite', models.CharField(max_length=50)),
                ('ecabout', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='emplor_reg',
            name='em_imgid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employermodule.em_img'),
        ),
        migrations.AddField(
            model_name='emplor_reg',
            name='em_reid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employermodule.emplor_cmre'),
        ),
    ]
