# Generated by Django 3.2.8 on 2021-12-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0002_auto_20211223_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='emplor_postjob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jobtitile', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=50)),
                ('jobdescription', models.CharField(max_length=1000)),
                ('skill', models.CharField(max_length=1000)),
                ('experiance', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=1000)),
                ('salary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='emplor_reg',
            name='jobpostid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employermodule.emplor_postjob'),
        ),
    ]
