# Generated by Django 3.2.8 on 2021-12-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0003_auto_20211225_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplor_reg',
            name='jobpostid',
        ),
        migrations.AddField(
            model_name='emplor_postjob',
            name='employerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employermodule.emplor_reg'),
        ),
    ]
