# Generated by Django 3.2.8 on 2021-12-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0004_auto_20211225_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='em_img',
            old_name='simg',
            new_name='eimg',
        ),
    ]
