# Generated by Django 3.2.8 on 2021-12-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0006_emplor_postjob_companyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplor_postjob',
            name='skill',
            field=models.CharField(choices=[('hello', 'hi'), ('ok', 'by'), ('Delivered', 'Delivered')], max_length=1000),
        ),
        migrations.AlterModelTable(
            name='emplor_postjob',
            table='employermodule_emplor_postjob',
        ),
    ]
