# Generated by Django 3.2.8 on 2021-12-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0007_auto_20211228_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplor_postjob',
            name='jobtype',
            field=models.CharField(choices=[('full time', 'full time'), ('intern', 'intern'), ('part time', 'part time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emplor_postjob',
            name='skill',
            field=models.CharField(max_length=1000),
        ),
    ]
