# Generated by Django 3.2.8 on 2022-01-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0010_alter_emplor_postjob_experiance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplor_postjob',
            name='skill',
        ),
        migrations.AddField(
            model_name='emplor_postjob',
            name='jobcategory',
            field=models.CharField(choices=[('Real Estate', 'Real Estate'), ('sale/marketing', 'sale/marketing'), ('education/training', 'education/training'), ('healthcare', 'healthcare'), ('science', 'science'), ('Technologies', 'Technologies'), ('art/Design', 'art/Design'), ('food services', 'food services')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emplor_postjob',
            name='skill1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='emplor_postjob',
            name='skill2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='emplor_postjob',
            name='skill3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='emplor_postjob',
            name='skill4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emplor_postjob',
            name='experiance',
            field=models.CharField(choices=[('fresher', 'fresher'), ('1 year', '1 year'), ('1 to 5 yea', '1 to 5 yea'), ('5 to 10 year', '5 to 10 year'), ('10 to 20 year', '10 to 20 year')], max_length=50),
        ),
    ]
