# Generated by Django 3.2.8 on 2022-01-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0011_auto_20220101_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employermodule.emplor_reg')),
            ],
        ),
    ]
