# Generated by Django 3.2.8 on 2022-01-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0012_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='seeker',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
