# Generated by Django 3.2.8 on 2022-01-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0013_auto_20220103_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mail',
            new_name='mail_msg',
        ),
    ]
